language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
os:
- linux
before_install:
- ./.travis/start-aerospike.sh
- cp .travis/slacktee.conf ~/.slacktee
install:
- sudo apt-get install autoconf libssl-dev
script:
- cd src/aerospike
- ./build.sh
- ../../.travis/load-extension.sh
- php pause-for-server.php
- cp ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini tmp-php.ini
- make test TESTS=tests/phpt TEST_PHP_ARGS="--show-diff"
after_failure:
- cat configure.in | ./scripts/slacktee.sh -t "$TRAVIS_REPO_SLUG $TRAVIS_JOB_NUMBER
  ($TRAVIS_COMMIT)" -f
- cat Makefile | ./scripts/slacktee.sh -t "$TRAVIS_REPO_SLUG $TRAVIS_JOB_NUMBER ($TRAVIS_COMMIT)"
  -f
after_script:
- ./scripts/slack-debug.sh
- ./scripts/test-cleanup.sh
notifications:
  slack:
    secure: CvYjLs0z+Y7NnhhoDLU61GSEKaPr0AM6fGrLHqqpXmNgl4AlaLSL46eSA6Zu/6cpnwr7m5REpjR6p4iNT57may783Ud+d89offuXK4nwiexi0MBPaPNb7MlBl07k1eOfX9GfbEYYo6vbp6q2DSn3RgrGIlyT20ocXPOLNJrh58U=
  hipchat:
    rooms:
      secure: R6iFduoL5HSUx634xGgNe4Rz4arm3M5oRoA2mJF7v5B0TO01jkac+Kpr5M30dUL1neHOBo1S446H9kI3M1QnfBxJLlBZST5P0xaJ1DsuLuN9FPs/h+0/gLZvATfCkjeJvZVKL8MyG/FwOuV18ciZ+XCg85qwJXqqvdahBk2S9TY=
  email:
    - qe-notices@aerospike.com
    - qe-notices-clients@aerospike.com
env:
  global:
  - secure: fJ2nIo5OYkrOFQFo/TXCqiyLXABuhYmLO8037ALplv3JbEZLMI7/NtZptKop+YZVO/HQ2jolWRVeKrXDY6ZDjdnI67hk+FSeIdhviNeWOoWEUt1Yk+YE6lLSFgtgZ0gI11hHrqqU9uzZ1h4MgkPpMPbA85O6RFWLrvjE9fcHLR4=
  - secure: 3zu4iH0VlDWPps9cT8Jz4LOsjKErbrqNabHqAKKHA1GfVZjd9C/UKxqjfCzF+F196rmZZgiOy5hG6zYPn9dM6JMpMPiKbnrguRTB6me79zP5FGWakp5B4IwkjQAm/eRCPa0VV3Ft//vG0/OgyrHQtrR0eFEDv1DVSonZ4s91QtM=
